name: blackhole
description: A Flutter Music Player.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 2.1.0+49

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  app_links: ^3.3.0
  audio_service: ^0.18.3
  audiotagger: ^2.2.1
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.3
  dart_des: ^1.0.0
  device_info: ^2.0.3
  file_picker: ^5.2.1
  flip_card: ^0.6.0
  flutter:
    sdk: flutter
  flutter_archive: ^5.0.0
  flutter_displaymode: ^0.4.0
  # flutter_downloader: ^1.7.1
  flutter_inapp_purchase: ^5.1.2
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  html_unescape: ^2.0.0
  just_audio: ^0.9.18
  # logging: ^1.0.1
  marquee: ^2.2.0
  material_design_icons_flutter: ^5.0.6295
  on_audio_query: ^2.5.3
  palette_generator: ^0.3.2
  path_provider: ^2.0.7
  permission_handler: ^10.1.0
  salomon_bottom_bar: ^3.1.0
  share_plus: ^4.5.3
  sliding_up_panel: ^2.0.0+1
  supabase: ^0.3.6
  syncfusion_flutter_sliders: ^20.3.49
  url_launcher: ^6.1.12
  uuid: ^3.0.5
  uni_links: ^0.5.0+2
  youtube_explode_dart: ^1.10.8
  flutter_launcher_icons: ^0.10.0
  intercom_flutter: ^7.5.0
  firebase_crashlytics: ^3.3.1
#  firebase_core: ^1.11.0
  firebase_core: ^2.13.0

  flutter_riverpod: ^2.0.2
  dartz: ^0.10.1
  shared_preferences: ^2.0.15
  package_info_plus: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2
  build_runner:
  flutter_gen_runner:
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launcher.jpg"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets to the application.
    - assets/

  fonts:
    - family: SharpSans
      fonts:
        - asset: assets/font/SharpSansBold.otf
        # - asset: assets/fonts/OpenSans-Bold.ttf
        # - asset: assets/fonts/OpenSans-Semibold.ttf
          weight: 700