// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDtd5SD91r6RFcyjAsqpDD3b3bg6cgv9U',
    appId: '1:990974183938:android:015daf455dbcd0e351b51b',
    messagingSenderId: '990974183938',
    projectId: 'yogitunes-ios',
    databaseURL: 'https://yogitunes-ios.firebaseio.com',
    storageBucket: 'yogitunes-ios.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE9MSfNr9NXh0bMEK5sykREoxuGPro1d0',
    appId: '1:990974183938:ios:52847b48c2b77ba6',
    messagingSenderId: '990974183938',
    projectId: 'yogitunes-ios',
    databaseURL: 'https://yogitunes-ios.firebaseio.com',
    storageBucket: 'yogitunes-ios.appspot.com',
    iosClientId: '990974183938-llq14lhl8bi0o9sc866ter6bvq9sn3tp.apps.googleusercontent.com',
    iosBundleId: 'net.mountainmandan.yogi-tunes',
  );
}
